### ISSUE TITLE
Transform VNode Properties

### ISSUE THREAD

**Issue by mikz** [rstacruz/decca#129]
I just spent few hours figuring out why my label elements have no for attribute (https://github.com/Matt-Esch/virtual-dom/issues/278).

Would be great to extend [`fixProps`](https://github.com/rstacruz/decca/blob/432b66dd8d7b9d7217a65c5f18355209a0481d3c/src/fix_props.js#L5-L23) to map [attributes to properties](https://github.com/wayfair/tungstenjs/blob/42535b17e4894e866abf5711be2266458bc4d508/src/template/template_to_vdom.js#L118-L140).

I think it is ok to just copy that list to keep 0 dependencies. 

If you are ok with it I'll make a PR.

**Comment by rstacruz** [comment]
Go for it!!

**Comment by mikz** [comment]
Done in #130
