### ISSUE TITLE
support pure components in string as well

### ISSUE THREAD

**Issue by borisirota** [rstacruz/decca#195]

**Comment by rstacruz** [comment]
Can you give an example use case how this can be useful?

**Comment by borisirota** [comment]
Sure => everyone who does server rendering.

Most of my components can be pure but I'm using server rendering so I cannot use this simplified version of components because its half supported.

**Comment by rstacruz** [comment]
Oh! I see. I thought you meant passing strings as a component. This should
be easy enough, PRs welcome if you manage to do it :)

**Comment by borisirota** [comment]
The PR is waiting :)

**Comment by rstacruz** [comment]
v2.2.2 is out. Thanks for your help!

So what are you using Decca for?

**Comment by borisirota** [comment]
Thanks. I'm using `deku`, but it seems that the project isn't maintained anymore + I like the fact `decca` uses `virtual-dom` so I'm thinking to switch.

There is not much activity in the [virtual-dom](https://github.com/Matt-Esch/virtual-dom) project as well, any idea ?

**Comment by borisirota** [comment]
BTW, you can remove the `simpler-debounce` dependency in the `package.json` because I didn't find uses of it.
