### ISSUE TITLE
make path to be deterministic like in deku

### ISSUE THREAD

**Issue by borisirota** [rstacruz/decca#204]
Hi, as noted [here](https://github.com/rstacruz/decca/blob/master/docs/about-deku.md#differences-with-deku) the difference between `decca` and `deku` is that the path isn't deterministic in decca and it isn't relative to it's ancestors, but rather increasing counter => same ui which reflects the same state will be with different ids at different points in time.

This can lead to some issues when the path has additional meaning.
For example, [deku-stateful](https://github.com/rstacruz/deku-stateful) uses the path as unique identifier for the component's state. I'm using the same approach, only I'm storing this inside the redux store and not attached to the component's instance.
It breaks for example when using time travel, because every creation of component generates new id but the state of this component exists in the key which is the first id.

Its even stated in [deku documentation](https://github.com/anthonyshort/deku/blob/master/docs/basics/components.md#components) -> `Components are: ... Uniquely identifiable using the path value, allowing you to store local state;`

It seems like the deterministic id and increasing counter fulfills the same function as a unique identifier but it isn't the case when the id has another meaning.

Currently, in my use case, I cannot switch from `deku` to `decca` because of that.

What are your thoughts about changing the id to be deterministic like in `deku` so it can really be 100% drop-in replacement ?

Thanks !

**Comment by rstacruz** [comment]
It should be deterministic in the sense that you're assured that the same
Id will be used if the component is the same instance, so deku-stateful is
a perfect fit for Decca. Have you tried them together?

**Comment by borisirota** [comment]
Yes I'm using it as well and in this case there is no problem. The problem arises when using the path as the unique identifier of the local component's state inside external store (redux) - the original purpose of the path as stated in [deku docs](https://github.com/anthonyshort/deku/blob/master/docs/basics/components.md#components).

_I'm storing inside redux all the state except global listeners like click, keydown, etc. (functions which should be removed when the component is being unmounted) which are stored inside `deku-stateful` for UX purposes (closing modal with esc or click outside it, etc.)_

Take for example the next scenario - we have app with one component which stores its state inside redux as `state[path] = COMPONENT_STATE` and we have a toggle for the component's visibility (dom removal).

step 1 - the component is visible and the state is `state[1] = COMPONENT_STATE`
step 2 (pressing the toggle) - the component removed from dom and the state is `state = {}`

Now, if using time travel and going back to the first step the state will be `state[1] = COMPONENT_STATE` but the path of the newly created component will be 2, going back to step 2 and back to step 1 will make the path to be 3 and so on.

In my perspective, we are talking about pure components and the functional way `deku` works is first of all avoid instances and second is that for the same input (state) we should get the exact same output (ui), but in `decca` we are getting back different output (as far as the path is concerned with its effects) for the same input state and I showed in the example above where it breaks.

**Comment by borisirota** [comment]
I thought about it in the last few days and what lead to this situation in my implementation was deku's suggestion to fire an action on onCreate hook in order to store local state under the relevant path key. This behavior breaks time travel since components can dispatch actions on creation and removal while time traveling and then when coming back to the last state there are some additional actions which doesn't reflect the current UI state. I stopped using local state this way and prefer deku-stateful for that purpose because no implicit actions being fired which changes the store.

**Comment by rstacruz** [comment]
Using the path as a key for the component state is also the primary use
case of it in Decca, just as with Deku. Any deviation from this is a bug.
if the path changes unexpectedly, try adding a `key` on the element that
the component's render() returns and see if it helps.

Thanks for writing about your insights!
